# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(default='', max_length=4)),
                ('type', models.CharField(default='', max_length=15)),
                ('name', models.CharField(default='', max_length=255)),
                ('latitude_deg', models.FloatField(default=0.0)),
                ('longitude_deg', models.FloatField(default=0.0)),
                ('elevation_ft', models.IntegerField()),
                ('continent', models.CharField(default='', max_length=2)),
                ('iso_country', models.CharField(default='', max_length=2)),
                ('iso_region', models.CharField(default='', max_length=5)),
                ('municipality', models.CharField(default='', max_length=255)),
                ('scheduled_service', models.CharField(default='no', max_length=3)),
                ('gps_code', models.CharField(default='', max_length=4)),
                ('iata_code', models.CharField(default='', max_length=3)),
                ('local_code', models.CharField(default='', max_length=4)),
                ('home_link', models.CharField(default='', max_length=255)),
                ('wikipedia_link', models.CharField(default='', max_length=255)),
                ('keywords', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
